# Generated by Django 3.2.23 on 2023-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('number_of_guests', models.IntegerField(choices=[(1, '1 person'), (2, '2 person'), (3, '3 person'), (4, '4 person'), (5, '5 person'), (6, '6 person'), (7, '7 person')], default=1)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
            ],
        ),
    ]
