# Generated by Django 3.2.3 on 2023-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_alter_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(choices=[(1, '1 guest'), (2, '2 guests'), (3, '3 guests'), (4, '4 guests'), (5, '5 guests'), (6, '6 guests')], default=1),
        ),
    ]
