# Generated by Django 3.2.3 on 2023-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_auto_20231125_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='number_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
