# Generated by Django 3.2.3 on 2023-11-27 08:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_auto_20231126_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
