# Generated by Django 3.2.3 on 2023-11-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
