# Generated by Django 3.2.3 on 2023-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_remove_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='12:00', max_length=100),
        ),
    ]
